
//LOGIN CONSTANTS
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_LOGIN = 'CHANGE_LOGIN';
export const IS_FETCHING = 'IS_FETCHING';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_NOT_RECEIVED = 'USER_NOT_RECEIVED';
export const RESET_FAIL = 'RESET_FAIL';
export const LOGOUT = 'LOGOUT';
export const DEFINE_USER = 'DEFINE_USER';


//PAGES CONSTANTS
export const CURRENT_PAGE_IS_FETCHING = 'CURRENT_PAGE_IS_FETCHING';
export const CURRENT_PAGE_CONTROL_RECEIVED = 'CURRENT_PAGE_CONTROL_RECEIVED';
export const CURRENT_PAGE_RECEIVED = 'CURRENT_PAGE_RECEIVED';
export const PAGES_RECEIVED = 'PAGES_RECEIVED';


//ICONS

export const ICONS_RECEIVED = 'ICONS_RECEIVED';